name: Test

on:
  push:
    paths:
      - "iter/**/*.go"
  pull_request:
    paths:
      - "iter/**/*.go"

jobs:
  run-tests:
    name: Run iter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Run tests
        run: make -C iter test
