name: Code Test Coverage

on:
  push:
    branches: "*"

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          make coverage
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
